name: AdminTools
version: 1.0-SNAPSHOT-15
main: com.riverstone.unknown303.admintools.AdminToolsPlugin
description: A PaperMC plugin adding AdminTools to Minecraft!
author: Unknown_303
api-version: '1.18'
depend: [NBTAPI, CommandAPI]